name: Gradle Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  buildShipsSponge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build Sponge with Gradle
        run: ./gradlew ShipsToSponge:buildPlugin
      - uses: actions/upload-artifact@v2
        with:
          name: "Ships-Sponge-StandAlone"
          path: "build"
  buildTranslateShips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build Ships with translate
        run: ./gradlew ShipsForCore:build
      - uses: actions/upload-artifact@v2
        with:
          name: "Ships-For-Translate-Core"
          path: "ShipsForCore/build/libs/*.jar"
  buildTranslateBukkit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build Bukkit with Gradle
        run: ./gradlew CoreToBukkit:buildPlugin
      - uses: actions/upload-artifact@v2
        with:
          name: "Bukkit-Translate-Core"
          path: "build"
  buildStandAloneBukkit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build Bukkit with Gradle
        run: ./gradlew CoreToBukkit:buildPlugin
      - name: Build Ships with Gralde
        run: ./gradlew ShipsForCore:build
      - name: Combine two
        run: java -cp ./build/TranslateCoreBukkit.jar org.core.terminal.Terminal jar ShipsForCore/build/libs/ShipsForCore-1.0-SNAPSHOT.jar main org.ships.plugin.ShipsPlugin
      - uses: actions/upload-artifact@v2
        with:
          name: "Ships-Bukkit-Standalone"
          path: *.jar