name: Gradle Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  testShips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run all tests
        run: ./gradlew test
      - name: Clean
        run: ./gradlew clean
      - name: Run translate core
        run: './gradlew :ShipsForCore:build'
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: "Ships For Core"
          path: "ShipsForCore/build/libs/*.jar"
  buildShipsSponge:
    needs: [ testShips ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build Sponge with Gradle
        run: ./gradlew buildSponge
      - uses: actions/upload-artifact@v3
        with:
          name: "Standalone-Ships-Sponge"
          path: "standalone/ShipsSponge.jar"
  buildTranslateFolia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Folia with Gradle
        run: ./gradlew buildPaper
      - uses: actions/upload-artifact@v3
        with:
          name: "TranslateCore-Folia-And-Paper"
          path: "standalone/ShipsFolia.jar"
  buildTranslateFolia1-19-4:
    needs: [ buildTranslateFolia ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Bukkit with Gradle
        run: ./gradlew buildPaper -P folia-api-version=1.19.4 -P use-paper=true
  buildStandAloneFolia:
    needs: [ buildTranslateFolia, testShips ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Folia with Gradle
        run: ./gradlew buildFolia
      - uses: actions/upload-artifact@v3
        with:
          name: "Standalone-Ships-Folia-And-Paper"
          path: "standalone/ShipsFolia.jar"
