name: Gradle Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  testShips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run all tests
        run: ./gradlew test
  buildShipsSponge:
    needs: [ buildTranslateShips ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Sponge with Gradle
        run: ./gradlew ShipsToSponge:buildPlugin
      - uses: actions/upload-artifact@v2
        with:
          name: "Standalone-Ships-Sponge"
          path: "build"
  buildTranslateShips:
    needs: [ testShips ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Ships with translate
        run: ./gradlew ShipsForCore:build
      - uses: actions/upload-artifact@v2
        with:
          name: "Ships-For-Core"
          path: "ShipsForCore/build/libs/*.jar"
  buildTranslateBukkit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Bukkit with Gradle
        run: ./gradlew CoreToBukkit:buildPlugin
      - uses: actions/upload-artifact@v2
        with:
          name: "TranslateCore-Bukkit"
          path: "build"
  buildTranslateBukkit1-19-3:
    needs: [ buildTranslateBukkit ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Bukkit with Gradle
        run: ./gradlew CoreToBukkit:buildPlugin -P paper-api-version=1.19.3
  buildTranslateBukkit1-17-1:
    needs: [ buildTranslateBukkit ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Bukkit with Gradle
        run: ./gradlew CoreToBukkit:buildPlugin -P paper-api-version=1.17.1
  buildStandAloneBukkit:
    needs: [ buildTranslateBukkit, buildTranslateShips ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Bukkit with Gradle
        run: ./gradlew CoreToBukkit:buildPlugin
      - name: Build Ships with Gradle
        run: ./gradlew ShipsForCore:build
      - name: Combine two
        run: java -cp ./build/TranslateCoreBukkit.jar org.core.terminal.Terminal jar ShipsForCore/build/libs/ShipsForCore-6.0.0.0-Beta.jar main org.ships.plugin.ShipsPlugin
      - uses: actions/upload-artifact@v2
        with:
          name: "Standalone-Ships-Bukkit"
          path: "*.jar"
