name: Gradle Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  buildSponge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build Sponge with Gradle
        run: ./gradlew ShipsToSponge:buildPlugin
      - uses: actions/upload-artifact@v2
        with:
          name: "Sponge"
          path: "build"
  buildBukkit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build Bukkit with Gradle
        run: ./gradlew ShipsToBukkit:buildPlugin
      - uses: actions/upload-artifact@v2
        with:
          name: "Bukkit"
          path: "build"
