name: Gradle Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  testShips:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run all tests
        run: ./gradlew test
  buildShipsSponge:
    needs: [ buildTranslateShips ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build Sponge with Gradle
        run: ./gradlew ShipsToSponge:buildPlugin
      - uses: actions/upload-artifact@v3
        with:
          name: "Standalone-Ships-Sponge"
          path: "build"
  buildTranslateShips:
    needs: [ testShips ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build Ships with translate
        run: ./gradlew ShipsForCore:build
      - uses: actions/upload-artifact@v3
        with:
          name: "Ships-For-Core"
          path: "ShipsForCore/build/libs/*.jar"
  buildTranslateBukkit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build Bukkit with Gradle
        run: ./gradlew CoreToBukkit:plugin
      - uses: actions/upload-artifact@v3
        with:
          name: "TranslateCore-Bukkit"
          path: "CoreToBukkit/build/libs/TranslateCoreBukkit.jar"
  buildTranslateFolia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Folia with Gradle
        run: ./gradlew CoreToFolia:plugin
      - uses: actions/upload-artifact@v3
        with:
          name: "TranslateCore-Folia"
          path: "CoreToFolia/build/libs/TranslateCoreFolia.jar"
  buildTranslateBukkit1-19-4:
    needs: [ buildTranslateBukkit ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Bukkit with Gradle
        run: ./gradlew CoreToBukkit:plugin -P paper-api-version=1.19.4
  buildTranslateBukkit1-18-2:
    needs: [ buildTranslateBukkit ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Bukkit with Gradle
        run: ./gradlew CoreToBukkit:plugin -P paper-api-version=1.18.2
  buildStandAloneBukkit:
    needs: [ buildTranslateBukkit, testShips ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build Bukkit with Gradle
        run: ./gradlew buildBukkit
      - uses: actions/upload-artifact@v3
        with:
          name: "Standalone-Ships-Bukkit"
          path: "standalone/ShipsBukkit.jar"
  buildStandAloneFolia:
    needs: [ buildTranslateFolia, testShips ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Folia with Gradle
        run: ./gradlew buildFolia
      - uses: actions/upload-artifact@v3
        with:
          name: "Standalone-Ships-Folia"
          path: "standalone/ShipsFolia.jar"
