# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Upload Releases

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
  workflow_dispatch:
    

permissions:
  contents: read

jobs:
  buildFolia:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build CoreToFolia
      run: ./gradlew CoreToFolia:buildPlugin
    - name: Build ShipsForCore
      run: ./gradlew ShipsForCore:build
    - name: Combine two
      run: java -cp ./build/TranslateCoreFolia.jar org.core.terminal.Terminal jar ShipsForCore/build/libs/ShipsForCore-6.0.0.0-Beta.jar main org.ships.plugin.ShipsPlugin
    - name: Rename
      run: mv "Standalone - ShipsForCore-6.0.0.0-Beta.jar" "ShipsFolia.jar"
    - name: Temp upload
      uses: actions/upload-artifact@v3
      with:
        name: "Temp-Folia"
        path: "ShipsFolia.jar"
